#!/usr/bin/env python3
"""
echo — Discord webhook poster.

Posts to Discord channels without needing a bot token.
Just webhook URLs. Simple, reliable, no-auth-needed.

Handles: patch notes, announcements, polls, player interaction.
"""

import asyncio
import json
import logging
import os
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Optional

import httpx

logging.basicConfig(
    level=logging.INFO,
    format="[echo:discord] %(asctime)s %(levelname)s %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger("echo.discord")


@dataclass
class DiscordEmbed:
    title: str
    description: str
    color: int = 0x00D4FF  # halo-ai blue
    fields: list[dict] = None
    footer: str = ""
    thumbnail_url: str = ""
    timestamp: str = ""

    def to_dict(self) -> dict:
        embed = {
            "title": self.title,
            "description": self.description,
            "color": self.color,
        }
        if self.fields:
            embed["fields"] = self.fields
        if self.footer:
            embed["footer"] = {"text": self.footer}
        if self.thumbnail_url:
            embed["thumbnail"] = {"url": self.thumbnail_url}
        if self.timestamp:
            embed["timestamp"] = self.timestamp
        else:
            embed["timestamp"] = datetime.now(timezone.utc).isoformat()
        return embed


class WebhookPoster:
    """Posts messages to Discord via webhooks. No bot token needed."""

    def __init__(self):
        self.webhooks = {
            "announcements": os.getenv("DISCORD_WEBHOOK_ANNOUNCEMENTS", ""),
            "patch_notes": os.getenv("DISCORD_WEBHOOK_PATCHNOTES", ""),
            "bug_reports": os.getenv("DISCORD_WEBHOOK_BUGS", ""),
            "community": os.getenv("DISCORD_WEBHOOK_COMMUNITY", ""),
            "dev_log": os.getenv("DISCORD_WEBHOOK_DEVLOG", ""),
        }
        self.username = "echo"
        self.avatar_url = ""  # Set to echo's avatar URL

    async def post(
        self,
        channel: str,
        content: str = "",
        embeds: list[DiscordEmbed] = None,
    ) -> bool:
        """Post a message to a Discord channel via webhook."""
        webhook_url = self.webhooks.get(channel, "")
        if not webhook_url:
            log.warning("No webhook configured for channel: %s", channel)
            return False

        payload = {
            "username": self.username,
            "content": content,
        }
        if self.avatar_url:
            payload["avatar_url"] = self.avatar_url
        if embeds:
            payload["embeds"] = [e.to_dict() for e in embeds]

        try:
            async with httpx.AsyncClient() as client:
                resp = await client.post(webhook_url, json=payload, timeout=10)
                if resp.status_code in (200, 204):
                    log.info("Posted to %s: %s", channel, content[:60] or embeds[0].title if embeds else "")
                    return True
                else:
                    log.error("Discord error %d: %s", resp.status_code, resp.text)
                    return False
        except Exception as e:
            log.error("Failed to post to %s: %s", channel, e)
            return False

    async def announce_release(self, version: str, changes: list[str]) -> bool:
        """Post a release announcement."""
        embed = DiscordEmbed(
            title=f"🎮 Voxel Extraction {version} Released",
            description="A new version is live! Update now.",
            color=0x00FF88,
            fields=[
                {"name": "Changes", "value": "\n".join(f"• {c}" for c in changes[:10]), "inline": False},
            ],
            footer="halo-ai studios — powered by AI agents",
        )
        return await self.post("announcements", embeds=[embed])

    async def post_patch_notes(self, version: str, notes: str) -> bool:
        """Post detailed patch notes."""
        embed = DiscordEmbed(
            title=f"📋 Patch Notes — {version}",
            description=notes[:4000],  # Discord limit
            color=0x40C4FF,
            footer="Generated by echo • reviewed by sentinel",
        )
        return await self.post("patch_notes", embeds=[embed])

    async def announce_event(self, title: str, description: str) -> bool:
        """Post a community event announcement."""
        embed = DiscordEmbed(
            title=f"🎉 {title}",
            description=description,
            color=0xE040FB,
            footer="halo-ai studios",
        )
        return await self.post("announcements", embeds=[embed])

    async def post_bug_response(
        self, reporter: str, bug_id: str, status: str, response: str,
    ) -> bool:
        """Respond to a bug report."""
        embed = DiscordEmbed(
            title=f"🐛 Bug #{bug_id} — {status.upper()}",
            description=response,
            color=0xFF4444 if status == "open" else 0x00FF88,
            fields=[
                {"name": "Reporter", "value": reporter, "inline": True},
                {"name": "Status", "value": status, "inline": True},
            ],
            footer="Tracked by bounty • responded by echo",
        )
        return await self.post("bug_reports", embeds=[embed])

    async def post_dev_log(self, title: str, content: str) -> bool:
        """Post a dev log / behind-the-scenes update."""
        embed = DiscordEmbed(
            title=f"🔧 Dev Log — {title}",
            description=content[:4000],
            color=0xFF6600,
            footer="halo-ai studios dev team",
        )
        return await self.post("dev_log", embeds=[embed])
